/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GiButton: typeof import('./components/button/src/index.vue')['default']
    GiCard: typeof import('./components/card/src/index.vue')['default']
    GiCheckboxGroup: typeof import('./components/checkbox-group/src/index.vue')['default']
    GiDialog: typeof import('./components/dialog/src/index.vue')['default']
    GiEditTable: typeof import('./components/edit-table/src/index.vue')['default']
    GiForm: typeof import('./components/form/src/index.vue')['default']
    GiGridGrid: typeof import('./components/grid/src/grid.vue')['default']
    GiGridGridItem: typeof import('./components/grid/src/grid-item.vue')['default']
    GiInputGroup: typeof import('./components/input-group/src/index.vue')['default']
    GiPageLayout: typeof import('./components/page-layout/src/index.vue')['default']
    GiRadioGroup: typeof import('./components/radio-group/src/index.vue')['default']
    GiSelect: typeof import('./components/select/src/index.vue')['default']
    GiTable: typeof import('./components/table/src/index.vue')['default']
    GiTabs: typeof import('./components/tabs/src/index.vue')['default']
  }
}
