/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonSrc: typeof import('./components/button/src/index.vue')['default']
    CardSrc: typeof import('./components/card/src/index.vue')['default']
    CheckboxGroupSrc: typeof import('./components/checkbox-group/src/index.vue')['default']
    DialogSrc: typeof import('./components/dialog/src/index.vue')['default']
    EditTableSrc: typeof import('./components/edit-table/src/index.vue')['default']
    FormSrc: typeof import('./components/form/src/index.vue')['default']
    GridSrcGrid: typeof import('./components/grid/src/grid.vue')['default']
    GridSrcGridItem: typeof import('./components/grid/src/grid-item.vue')['default']
    InputGroupSrc: typeof import('./components/input-group/src/index.vue')['default']
    PageLayoutSrc: typeof import('./components/page-layout/src/index.vue')['default']
    RadioGroupSrc: typeof import('./components/radio-group/src/index.vue')['default']
    SelectSrc: typeof import('./components/select/src/index.vue')['default']
    TableSrc: typeof import('./components/table/src/index.vue')['default']
    TabsSrc: typeof import('./components/tabs/src/index.vue')['default']
  }
}
