/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GiButton: typeof import('./components/button/src/button.vue')['default']
    GiCard: typeof import('./components/card/src/card.vue')['default']
    GiDialog: typeof import('./components/dialog/src/dialog.vue')['default']
    GiEditTable: typeof import('./components/edit-table/src/edit-table.vue')['default']
    GiForm: typeof import('./components/form/src/form.vue')['default']
    GiGrid: typeof import('./components/grid/src/grid.vue')['default']
    GiGridItem: typeof import('./components/grid/src/grid-item.vue')['default']
    GiInputGroup: typeof import('./components/input-group/src/input-group.vue')['default']
    GiInputSearch: typeof import('./components/input-search/src/input-search.vue')['default']
    GiPageLayout: typeof import('./components/page-layout/src/page-layout.vue')['default']
    GiSplitButton: typeof import('./components/page-layout/src/split-button.vue')['default']
    GiTable: typeof import('./components/table/src/table.vue')['default']
    GiTableColumn: typeof import('./components/table/src/TableColumn.vue')['default']
    GiTabs: typeof import('./components/tabs/src/tabs.vue')['default']
  }
}
